In [1]:
import pandas as pd
import os

In [5]:
# os.listdir('/kaggle/input/')
cst  = pd.read_csv('olist_customers_dataset.csv')
cst.head(1)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP

In [6]:
loc  = pd.read_csv('olist_geolocation_dataset.csv')
loc.head(1)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP

In [7]:
items  = pd.read_csv('olist_order_items_dataset.csv')
items.head(1)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29

In [8]:
payments  = pd.read_csv('olist_order_payments_dataset.csv')
payments.head(1)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33

In [9]:
review  = pd.read_csv('olist_order_reviews_dataset.csv')
review.head(1)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59

In [10]:
orders  = pd.read_csv('olist_orders_dataset.csv')
orders.head(1)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00

In [11]:
products  = pd.read_csv('olist_products_dataset.csv')
products.head(1)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0

In [12]:
sellers  = pd.read_csv('olist_sellers_dataset.csv')
sellers.head(1)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP

In [14]:
categories  = pd.read_csv('product_category_name_translation.csv')
categories.head(1)

  product_category_name product_category_name_english
0          beleza_saude                 health_beauty

In [21]:
x = pd.to_datetime(orders['order_purchase_timestamp']).dt.year.value_counts()/len(orders) *100

In [22]:
x

order_purchase_timestamp
2018    54.314619
2017    45.354532
2016     0.330849
Name: count, dtype: float64